-- Atualiza tabela PRODUTO para controle por empresa
ALTER TABLE PRODUTO
  ADD COLUMN VALOR_COMPRA DECIMAL(10,2) NOT NULL DEFAULT 0.00 AFTER ID_MARCA,
  ADD COLUMN ID_EMPRESA INT AFTER VALOR_COMPRA;

ALTER TABLE PRODUTO
  DROP INDEX CODIGO,
  ADD UNIQUE KEY UQ_PROD_CODIGO_EMPRESA (CODIGO, ID_EMPRESA);

ALTER TABLE PRODUTO
  ADD CONSTRAINT FK_PRODUTO_EMPRESA FOREIGN KEY (ID_EMPRESA)
    REFERENCES EMPRESA(ID);
