-- Atualiza tabela VENDAS conforme novo modelo
ALTER TABLE VENDAS
  DROP COLUMN FORMA_PAGAMENTO,
  DROP COLUMN NUMERO_PARCELAS,
  DROP COLUMN DATA_VENCIMENTO_PARCELA;

ALTER TABLE VENDAS
  ADD COLUMN ID_METODO_PAGAMENTO INT,
  ADD COLUMN JUROS_APLICADO DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN VALOR_LIQUIDO DECIMAL(10,2) NOT NULL;

ALTER TABLE VENDAS
  ADD CONSTRAINT FK_VENDAS_METODO FOREIGN KEY (ID_METODO_PAGAMENTO)
    REFERENCES METODO_PAGAMENTO(ID);
